fix sample track out of sync with jack on 48000 hz
LMMS/lmms pull request #4975
Opened 2019-05-16 13:08 UTC by BaraMGB

fixes  https://github.com/LMMS/lmms/issues/4786

2019-05-24 14:44 UTC, Spekular commented
For whatever my code review is worth:

No cosmetic issues since you're just replacing functions, no concern about the actual logic of the fix either. Have you tested if this fix works with oversampling enabled?

2019-05-24 15:17 UTC, Spekular approved these changes

2019-05-25 08:36 UTC, Spekular requested changes

2019-05-25 08:36 UTC, Spekular commented on src/core/SampleBuffer.cpp
>  	// do samplerate-conversion to our default-samplerate
```suggestion
	// do samplerate-conversion to our processing-samplerate
```

2019-05-25 08:39 UTC, Spekular commented on src/core/SampleBuffer.cpp
>  	// do samplerate-conversion to our default-samplerate
On second thought, this comment should be changed, unless this line was changed by mistake.

2019-05-25 18:32 UTC, BaraMGB commented
I close this in favor of a solution of @Reflexe

2019-05-25 18:32 UTC, closed without merging