SampleBuffer -> Samplerate - Fix two sample rate issues:
LMMS/lmms pull request #4991
Opened 2019-05-25 19:16 UTC by Reflexe

1. Resampling was the wrong (src_rate was invalid)
2. SampleBuffer was using baseSampleRate as the default samplerate
instead of the actual processingSampleRate.

Closes #4975

2019-05-28 12:10 UTC, BaraMGB requested changes

2019-05-28 12:10 UTC, BaraMGB commented on src/core/SampleBuffer.cpp
> +	return Engine::mixer ()->processingSampleRate ();
there is a space between Engine::mixer and ()->

2019-05-28 12:10 UTC, BaraMGB commented on src/core/SamplePlayHandle.cpp
> +	return ( m_sampleBuffer->endFrame() - m_sampleBuffer->startFrame() ) * ( Engine::mixer()->processingSampleRate() / m_sampleBuffer->sampleRate ());
There should be a space before the last brace. I Know, we have different styles in different files. That should be fixed in the whole code base. It's annoying to fix those spaces. Sorry for that.

2019-05-28 12:12 UTC, BaraMGB commented
>  Closes #4975

Should be https://github.com/LMMS/lmms/issues/4786

2019-05-28 12:18 UTC, BaraMGB commented
https://github.com/LMMS/lmms/issues/4786 is not fixed with this PR. :confused:

2019-05-28 18:18 UTC, Reflexe commented
Ok, I've found the right commit. However, I can't understand how your solution has solved it? :\

2019-05-29 08:47 UTC, BaraMGB commented on src/core/SampleBuffer.cpp
> +		src_data.src_ratio = (double) _src_sr / _dst_sr;
My Jack is running on 48Khz. I have a click track. I export the project *.wav with 44,1 khz. I insert the *.wav to a sample track. It isn't in sync:
![Bildschirmfoto von 2019-05-29 10-37-38](https://user-images.githubusercontent.com/6502580/58543012-dc58e380-81fe-11e9-9c4f-fee53f266c06.png)

If I revert this line (_dst_sr / _src_sr) it is in sync:

![Bildschirmfoto von 2019-05-29 10-39-19](https://user-images.githubusercontent.com/6502580/58543102-08746480-81ff-11e9-9fee-e08991831025.png)

2019-05-29 08:52 UTC, Reflexe commented
Thanks! I'll look into that in a few hours.

On Wed, 29 May 2019, 11:47 Steffen Baranowsky, <notifications@github.com>
wrote:

> *@BaraMGB* commented on this pull request.
> ------------------------------
>
> In src/core/SampleBuffer.cpp
> <https://github.com/LMMS/lmms/pull/4991#discussion_r288457053>:
>
> > @@ -1196,7 +1201,7 @@ SampleBuffer * SampleBuffer::resample( const sample_rate_t _src_sr,
>  		src_data.data_out = dst_buf[0];
>  		src_data.input_frames = frames;
>  		src_data.output_frames = dst_frames;
> -		src_data.src_ratio = (double) _dst_sr / _src_sr;
> +		src_data.src_ratio = (double) _src_sr / _dst_sr;
>
> My Jack is running on 48Khz. I have a click track. I export the project
> *.wav with 44,1 khz. I insert the *.wav to a sample track. It isn't in sync:
> [image: Bildschirmfoto von 2019-05-29 10-37-38]
> <https://user-images.githubusercontent.com/6502580/58543012-dc58e380-81fe-11e9-9c4f-fee53f266c06.png>
>
> If I revert this line (_dst_sr / _src_sr) it is in sync:
>
> [image: Bildschirmfoto von 2019-05-29 10-39-19]
> <https://user-images.githubusercontent.com/6502580/58543102-08746480-81ff-11e9-9fee-e08991831025.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/LMMS/lmms/pull/4991?email_source=notifications&email_token=AFOMGKCRTHMBXKI5NG4IKNTPXY7J7A5CNFSM4HPVG4AKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOBZ63ARQ#pullrequestreview-243118150>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFOMGKFLPCHJROEUMPSEOWDPXY7J7ANCNFSM4HPVG4AA>
> .
>

2019-05-29 19:32 UTC, Reflexe commented
Oky dooky, I think we are good now (I fixed that in another commit probably :\) Thanks for your help!

2019-06-02 14:02 UTC, BaraMGB requested changes
The issue is fixed with this PR, now. After fixing these 2 style issues I vote for merge.

2019-06-02 14:02 UTC, BaraMGB commented on src/core/Engine.cpp
> +float LmmsCore::framesPerTick(sample_rate_t sample_rate)  {
The curled brace belongs in the next line.

2019-06-02 17:48 UTC, Reflexe commented
Since it isn't a single issue, I'll rebase it.

2019-06-02 17:48 UTC, merged