Rename MidiTime to TimePos
LMMS/lmms pull request #5684
Opened 2020-09-25 22:17 UTC by M374LX

Redoing  #4897 and #5295 after both were unsuccessfully closed.

Closes #4866.

2020-09-25 22:23 UTC, Spekular commented
This looks like a good candidate to be part of #5592 which is targeted around December.

2020-11-29 11:17 UTC, JohannesLorenz requested changes
Only 3 minor comments.

If you make changes, please add new commits (instead of squashing), so I don't need to review this large diff again ;) I'll squash it together when merging then.

2020-11-29 11:17 UTC, JohannesLorenz commented on include/TimePos.h
> -class LMMS_EXPORT MidiTime
Only in case you learned what this class does: Can you please add a doxygen comment above it? (Same for `TimeSig`, also voluntarily).

2020-11-29 18:44 UTC, JohannesLorenz approved these changes
All good, thanks for the PR!

I'll merge this right now.

2020-11-29 18:46 UTC, merged