Use QSaveFile on file write
LMMS/lmms pull request #6107
Opened 2021-07-22 05:35 UTC by zonkmachine

Fixes #4514 by replacing QFile with QSaveFile on save action.

2021-08-03 12:00 UTC, Spekular approved these changes
LGTM. Merge?

2021-08-03 12:05 UTC, Spekular commented
Actually though, aren't we doing duplicate work? QSaveFile already uses a temporary file, so we can probably write directly to the final filename now, no?

2021-08-03 12:06 UTC, Spekular requested changes
Approved too fast (only looked at diff). Upon closer inspection, it seems like we should remove our homebrewed temp file since QSaveFile already uses the same method.

2021-08-28 21:04 UTC, DomClark commented
Prior to this PR, the backup file was the old version of the project file, before being saved. Now, it is identical to the newly-saved version. Is this intended? It doesn't strike me as particularly useful.

2021-08-28 21:20 UTC, zonkmachine commented
Right. Looking into it.

2021-08-29 14:27 UTC, zonkmachine commented
After discussion on Discord `#dev-only` fullNameTemp is now back. I just dropped the file size check which is now redundant.
Saving with and without backup file works.

2021-08-29 14:55 UTC, zonkmachine commented
Now after the QSaveFile commit() is performed we still do a bunch of QFile actions and the commited file could end up either in fullName + ".new" or being deleted if one of the QFile::remove(...)/QFile::rename(...), for whatever reason, fails.

2021-08-29 16:10 UTC, zonkmachine commented
Also, if a save operation fail it returns `false`, but it doesn't look like we act on that everytime we save. We do when using `MainWindow::mayChangeProject()` such as in `MainWindow::closeEvent()`.

2021-08-29 18:19 UTC, zonkmachine commented on src/core/DataFile.cpp
> +			SongEditor::tr("An unknown error has occured and the file could not be saved."));
outfile.errorString() goes in here...

2021-10-31 21:57 UTC, zonkmachine commented
I would be jolly happy if someone whould like to take over this issue/PR. @Spekular?
I don't feel confident enough with the coding here and I'm to rusty anyway. Just grab the code.. :) Plz...

2023-06-29 14:26 UTC, zonkmachine commented on src/core/DataFile.cpp
> +			SongEditor::tr("An unknown error has occured and the file could not be saved."));
^2 years later... What is that man on about?!

2023-11-03 21:21 UTC, Veratil approved these changes
Two quick style fixes and good to go

2023-11-03 21:21 UTC, Veratil commented on src/core/DataFile.cpp
> +	QSaveFile outfile (fullNameTemp);
```suggestion
	QSaveFile outfile(fullNameTemp);
```

2023-11-03 21:21 UTC, Veratil commented on src/core/DataFile.cpp
> +	if (ConfigManager::inst()->value("app", "disablebackup" ).toInt())
```suggestion
	if (ConfigManager::inst()->value("app", "disablebackup").toInt())
```

2023-11-03 21:37 UTC, merged

2023-11-03 21:38 UTC, zonkmachine commented
@Veratil Thanks!