Fixed issue of build when fpermissive isn't enabled
LMMS/lmms pull request #6231
Opened 2021-12-07 04:26 UTC by SeleDreams

lmms wouldn't build on my windows x64 setup due to the fact char* pointers have a long long size rather than a long size so I fixed it by changing the cast to long long, it should still work on platforms where long is used as the container type has enough place to contain the value

2021-12-07 05:29 UTC, Veratil commented
This is only fixing a build blocking issue, since we don't use portsmf to write MIDI.

2021-12-07 05:29 UTC, Veratil approved these changes

2021-12-07 12:44 UTC, rdrpenguin04 commented
Why are we not just using `uintptr_t`? That is the only type guaranteed to hold the value of a pointer by the C/++ specs.

2021-12-07 12:57 UTC, rdrpenguin04 commented
In fact, this entire statement looks very suspicious... Lemme try changing casts quick.

2021-12-07 20:10 UTC, rdrpenguin04 requested changes

2021-12-07 20:25 UTC, Veratil commented on plugins/MidiImport/portsmf/allegro.h
> +        assert((char *)(((long long) (ptr + 7)) & ~7) <= fence);
Again, this part of portsmf is not used in LMMS at all. We only use the read functionality, not the write. Clearing the error is enough.

2021-12-27 02:22 UTC, PhysSong commented on plugins/MidiImport/portsmf/allegro.h
> +        assert((char *)(((long long) (ptr + 7)) & ~7) <= fence);
This may add unnecessary casts on 32bit builds in some cases. I'm for `uintptr_t`, but this is definitely better than nothing.

2021-12-27 16:56 UTC, Veratil commented
Since this fixes a build issue I'm merging now.

2021-12-27 16:56 UTC, merged