minor changes in sf2 design
LMMS/lmms pull request #6474
Opened 2022-07-31 04:07 UTC by Rossmaxx

fixes #6454 and replaces #6473.

2022-07-31 16:38 UTC, YohananDiamond commented
Some small critiques:
![image](https://user-images.githubusercontent.com/23298480/182036381-09f313ae-4630-434a-9e8f-dd744a8547ad.png)
Other than that, it looks good! I just now wonder about the background - I personally like it but should it also be updated to follow the general design style that LMMS seems to be going towards?
By "this design" I mean stuff like the design in the Equalizer plugin:
![image](https://user-images.githubusercontent.com/23298480/182036443-b8c0fd27-d9bb-435b-a8ed-602caa0f0f2e.png)

2022-08-01 04:58 UTC, Rossmaxx commented
> some small critiques: 

The image

I felt like doing that but was not sure. I'll give it a shot.

> should it also be updated to follow the general design style that LMMS seems to be going towards?

I tried but the background i did in the old pr was not good so just reverted it. Anyway I'll try again once i get more ideas.

2022-08-09 04:39 UTC, Monospace-V commented
I'm actually quite a fan of the pinks in SF2. I feel like where orange-white:3o and warm brown: mallets, similarly phenolphthalein pinks: SF2 player.
As far as I understand, the only problems are the fact that bank and patch number is unreadable:
![image](https://user-images.githubusercontent.com/76674645/183563481-1ce2a534-a741-4d3b-89f4-bc85e7a4bbf0.png)

and maybe how the pink is too bright in the folder-browse icon:
![image](https://user-images.githubusercontent.com/76674645/183563573-407dda0d-5292-46e8-8763-3649505adfc2.png)

I think this can be easily remedied by making a new folder icon if needed, and changing bank/patch selection.

Looking at all other instruments,
TripleOscillator: Orange-white, white dials on main instrument plugin settings.
sfxr: black and multicoloured, multicoloured dials.
organic: grey and green, dials are green (and violet/dark pink for harm to differentiate)
OpulenZ- peacock colour, whatever it's called; dials are white
SID- pale yellow, dials are some white

While I feel there's nothing wrong with the fact SF2 player is themed pink, as it can be a rather good looking colour if used well,
![image](https://user-images.githubusercontent.com/76674645/183564359-48434efe-5328-4910-bafc-ced6d0547121.png)
![image](https://user-images.githubusercontent.com/76674645/183565423-0ddeb630-da7e-4e1c-b07d-c0f98be99d1c.png)
(I can't fix the icon, but presumably someone can.)

If you're going to make some parts of it green, then make all of it greenish, including the SF2 icon on the plugin sidebar and the text on top of the plugin. Having it green (whether to fit in with everything else or make it unique as an instrument) doesn't look good alongside pinks, and could be slightly visually unappealing.

2022-08-20 07:08 UTC, Rossmaxx commented
>  It appears this is now an entire redesign (for reasons I don't entirely understand)

i decided to redesign the entire thing because changing the lcds to green feels off. i can't change the lcds to pink either cause the pink one is broken. 

>  The art appears a lot less comfortable within its style than old

fixed along with the other design flaws

2022-08-20 10:13 UTC, Monospace-V commented
Then can I implore you to pick a different pink for LCDs instead of turning the entire plugin UI green?

The SF2 player design is similar to the design of some other LMMS plugins in terms of the partially 3d grey analogue knobby style.
Notice how the shadows and lights fall, the apparent depth.
Your design looks like only the GIG player.
![image](https://user-images.githubusercontent.com/76674645/185740195-f74b51b6-a347-400b-b53f-21a93b0361a0.png)
_SF2 player. Notice how the interface looks solid, and how there are ridges and raised surfaces. This will be our reference._

![image](https://user-images.githubusercontent.com/76674645/185740220-2dfee6f2-2fe2-40f7-99b0-d623b33a900c.png)
_AudioFileProcessor, look at the box which contains the sample waveform- to be specific, its lower and right edges._

![image](https://user-images.githubusercontent.com/76674645/185740244-8cedb23c-fe99-4109-b17e-d284cdd271bc.png)
_Kicker. The interface speaks for itself._

![image](https://user-images.githubusercontent.com/76674645/185740298-0471343f-0f52-4d21-bece-bc207a2776b9.png)
_Mallets. Visibly 3d around the edges of the interface box within the interface._

![image](https://user-images.githubusercontent.com/76674645/185740318-efa811a3-79fd-4ab9-b152-bc04c282f8ea.png)
_Monstro. The split between the tabs on the top and the instrument controls is a little jarring, being 2d and 3d respectively._

![image](https://user-images.githubusercontent.com/76674645/185740341-c4e1334b-7790-47b3-8d41-f67fc76c28c2.png)
_Organic. Again, distinctly 3d analogue look to it, with the screws and lighting._

![image](https://user-images.githubusercontent.com/76674645/185740351-7a076c5d-b0de-4eed-ad6e-06970b0cb823.png)
_GIG Player. 2d, plain because nobody else has looked at it in decades (who uses GIG files anymore?), inconsistent with the theming of every instrument having an at least unique if not 3d UI, but passable- again only because nobody uses GIG files._

![image](https://user-images.githubusercontent.com/76674645/185740499-7a6fa792-acc3-47d6-98de-ad708a160a60.png)
_VeSTige. Look at the box which contains the name of the VST._

(It should be noted that I'm probably biased towards the current appearance of the plugins as they are, though. I'm wont to complain about any new designs, especially ones that look so fundamentally different from the previous UI, the UI of other plugins, and my idealized good appearance of a UI. Maybe this could look better in app? I'll download and check.)

What application do you use for the UI design, OP?

2022-08-20 12:38 UTC, Rossmaxx commented
> What application do you use for the UI design, OP?

good ol' gimp.

> The SF2 player design is similar to the design of some other LMMS plugins in terms of the partially 3d grey analogue knobby style.

I agree but the for the new ui, I am looking at lost robot's compressor for inspiration. 

> Then can I implore you to pick a different pink for LCDs instead of turning the entire plugin UI green?

I asked the dev channels about the possibility before I started the work. The colour is not plain hex codes, instead the lcd num boxes use something called pixmaps which are not modifiable easily.

> It should be noted that I'm probably biased towards the current appearance of the plugins as they are, though. I'm wont to complain about any new designs, especially ones that look so fundamentally different from the previous UI, the UI of other plugins, and my idealized good appearance of a UI.

well, we all have our own tastes.

2022-08-20 12:40 UTC, Rossmaxx commented
@YohananDiamond what'd you think of the new design?

2022-08-20 18:56 UTC, YohananDiamond commented
Overall it looks nice, but here are some more nitpicks:
![image](https://user-images.githubusercontent.com/23298480/185762147-06bfe946-a2ca-488d-b9b4-810ed063cfa8.png)
Also, is it possible to use the modern-style knobs? I think they would look nice here and they're already being used on LB302 & BitInvader, for example.
![image](https://user-images.githubusercontent.com/23298480/185762204-9622d57b-9c9e-4f4e-902b-0dbccc017dc0.png)
![image](https://user-images.githubusercontent.com/23298480/185762262-5465e008-e6ce-4e9e-ab30-816aa59cbeff.png)

2022-08-21 04:09 UTC, Rossmaxx commented
> Also, is it possible to use the modern-style knobs? 

I asked the devs in the server. Waiting for a response. 

> The background colour looks weird

I noticed that one but not really sure on what to replace it with. Your suggestion looks good. Will try to do that one.

> Sf2 looks like sfz

That's accidental but it looks good so i think it's fine.

> Black background on the file button

I don't think it will create any issues so no need to change that one. Will change if any problems come up 

> Blurry text.

It's because of gimp pixelating the text on low resolutions. Haven't found any workarounds yet  

Thanks yohana diamond for your suggestions

2022-08-21 13:11 UTC, YohananDiamond commented
No problem!

> That's accidental but it looks good so i think it's fine.

I pointed it out because there's another format similar to sf2 called sfz, and it's not supported by LMMS (at least directly), so I think it would cause some confusion.

> I don't think it will create any issues so no need to change that one. Will change if any problems come up

I meant that the button right below has a gray background while this one has a black, and I found it kinda confusing

2022-08-22 05:41 UTC, Rossmaxx commented
> Also, is it possible to use the modern-style knobs? I think they would look nice here and they're already being used on LB302 & BitInvader, for example.

done

2022-08-22 17:25 UTC, YohananDiamond commented
Looks fine now! Though the open button background issue keeps on and maybe the knob could be slightly smaller (see comparison in the image)
![image](https://user-images.githubusercontent.com/23298480/185981705-e68f7cd4-20a8-4d24-8240-69945804524e.png)
Also, what if we made a background to put on where it's currently green? Something also green-ish but with some level of detail to make the plugin look more unique (which is a thing that I think it lost after redesigning it)
I'm gonna think about it and maybe I can come up with something soon, then I'll send it here

2022-08-23 14:20 UTC, RiedleroD commented
I haven't got time to contribute rn, but imo a PCB design could fit the green well.

2022-08-23 14:55 UTC, Rossmaxx commented
> I haven't got time to contribute rn, but imo a PCB design could fit the green well.

Noted. Will try when i get time

2022-08-27 07:38 UTC, Rossmaxx commented
@YohananDiamond @RiedleroD looks good? any more suggestions.

2022-08-27 08:08 UTC, RiedleroD commented
just a few tiny things. could you send me the gimp project file for that? I'll try to improve upon your design if that's ok.

2022-08-27 08:11 UTC, Rossmaxx commented
do you have discord? please dm me rossmaxx#9915. also, the gimp project file is a bit of a mess.

2022-08-28 16:29 UTC, YohananDiamond commented
Just checked it out and I think the idea looks good but it still needs some polishing.
- Again on the knobs: I noticed they aren't aligned with the text (I think this just involves offseting them horizontally a little bit more).
- The background is nice but I think some more lines would make things more vivid. These new lines could be a little bit closer to the background color so they don't catch the user's attention too much.
- Aliasing: too much on the button texts, too little on the big texts & the circles. I don't really know how to fix this properly, but here are some suggestions:
    - Make the yellow circles thicker and _maybe_ enable antialiasing;
    - Make it so the button texts are not bold;
    - Enable antialiasing on the "SF2" text;
but I think you can put antialiasing without fear on the circles and, for the fonts, also put antialiasing but, on the smaller ones

![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2F1.bp.blogspot.com%2F-Rqb7IHt8GME%2FXxlkd7BrQZI%2FAAAAAAAAAjA%2Fun_vBwcMq4s86Uh5B91Iop4LmwmAe6Q6gCLcBGAsYHQ%2Fw1200-h630-p-k-no-nu%2FPrinted%252BCircuit%252BBoard%252BDesign.jpg)

2022-08-29 08:17 UTC, sakertooth requested changes
Just some formatting adjustments.

2022-08-29 08:17 UTC, sakertooth commented on plugins/Sf2Player/Sf2Player.cpp
> +	m_chorusNumKnob = new Knob( knobBright_26, this );
```suggestion
	m_chorusNumKnob = new Knob(knobBright_26, this);
```

2022-08-29 08:17 UTC, sakertooth commented on plugins/Sf2Player/Sf2Player.cpp
> +	m_chorusSpeedKnob = new Knob( knobBright_26, this );
```suggestion
	m_chorusSpeedKnob = new Knob(knobBright_26, this);
```

2022-08-29 08:17 UTC, sakertooth commented on plugins/Sf2Player/Sf2Player.cpp
> +	m_chorusDepthKnob = new Knob( knobBright_26, this );
```suggestion
	m_chorusDepthKnob = new Knob(knobBright_26, this);
```

2022-08-29 12:11 UTC, Rossmaxx commented on plugins/Sf2Player/Sf2Player.cpp
> +	m_bankNumLcd = new LcdSpinBox( 3, "19green", this );
Fixed all the formatting issues.

2022-08-29 14:00 UTC, sakertooth reviewed
Just to resolve the accidental request for review from @Rossmaxx (He informed me that this was the case).

2022-09-26 07:00 UTC, Rossmaxx commented
The blurry text has been fixed. I installed and used inkscape for that

2023-01-25 14:52 UTC, Rossmaxx commented
closing this cause i don't got time to get it finished.

2023-01-25 14:52 UTC, closed without merging