Fixed the bug where mono VSTs only output on the left channel
LMMS/lmms pull request #6693
Opened 2023-04-20 08:51 UTC by QuixoticJk

Added a check for the amount of input channels and routed a single channel to both out channels if there is only one channel coming in, this should fix the problem of single inputs only getting processed into a single output channel

could still use some testing and might need some reformatting since its my first time using the lmms conventions and im still getting used to it

Fixes #6558

2023-04-20 09:46 UTC, superpaik commented on plugins/VstBase/RemoteVstPlugin.cpp
> +
```suggestion

```

2023-04-22 21:20 UTC, messmerd commented on .travis.yml
Why did you add this file?

2023-04-22 21:20 UTC, messmerd commented on plugins/VstBase/RemoteVstPlugin.cpp
A lot of your changes don't follow our style guidelines. See: https://github.com/LMMS/lmms/wiki/Coding-Conventions

2023-04-28 10:16 UTC, PhysSong commented
I think this might not be a proper way to fix the issue which you want to fix. Can you provide an example case where this pull request helps?

2023-05-14 04:31 UTC, messmerd commented
> I think this might not be a proper way to fix the issue which you want to fix. Can you provide an example case where this pull request helps?

It looks like this PR is meant to fix #6558.

2023-07-02 13:28 UTC, luzpaz commented
@QuixoticJk please respond :point_up_2:

2023-10-25 06:27 UTC, messmerd commented
It seems that @QuixoticJk isn't responding so I will give them another week and then take over this PR.

2024-04-12 14:33 UTC, zonkmachine commented
Any suggestions for vsts to test this? In https://github.com/LMMS/lmms/issues/6558 is suggested JuceOPLVSTi but that one won't load for me.

2024-04-12 15:02 UTC, messmerd commented
I introduced a class called [`PluginPortConfig`](https://github.com/LMMS/lmms/pull/7199/files#diff-d965b73cba01403359847a8d5d3d5096170582e2f30ff2ab6346e2dfa1d18a7b) in my CLAP plugin PR as a general purpose solution for routing audio in and out of mono plugins. Maybe I should spin it off into its own PR to solve this problem with mono VSTs.

2024-04-14 11:19 UTC, zonkmachine commented
> I introduced a class called [`PluginPortConfig`](https://github.com/LMMS/lmms/pull/7199/files#diff-d965b73cba01403359847a8d5d3d5096170582e2f30ff2ab6346e2dfa1d18a7b) in my CLAP plugin PR as a general purpose solution for routing audio in and out of mono plugins. Maybe I should spin it off into its own PR to solve this problem with mono VSTs.

Yes. Do you mean merging this and then refactor it later?
PS. I'm still looking for plugins to test this PR/issue.

2024-04-14 12:04 UTC, DomClark requested changes
As PhysSong suggests, the changes in this PR are incorrect. This puts what should be two sequential buffers into the left and right channels. The correct behaviour is to process a single buffer, and fill both channels with the same data.

2024-05-08 08:01 UTC, messmerd commented
This PR is superseded by #7247.

2024-05-08 08:02 UTC, messmerd commented
Closing in favor of #7247.

2024-05-08 08:02 UTC, closed without merging