Add Continuous Auto-Scrolling
LMMS/lmms pull request #7396
Opened 2024-07-26 02:14 UTC by regulus79

This pull request adds the option to have auto-scrolling continuously scroll the view to keep up with the playback.

## Changes
- New icons for Stepped/Continuous auto-scrolling
- `AutoScrollState` enum changed from `Enabled`/`Disabled` to `Stepped`/`Continuous`/`Disabled`
- The auto-scroll button in `TimeLineWidget.cpp` is changed from having 2 states (`Enabled`/`Disabled`) to having 3 states (`Stepped`/`Continuous`/`Disabled`)
- In the code for auto-scrolling in both `SongEditor.cpp` and `PianoRoll.cpp`, a check is added for whether the mode is `Stepped` or `Continuous`; if it's `Stepped`, then is runs the old code for auto-scrolling; if it's `Continuous`, then it snaps the horizontal scroll to halfway behind the time line so that the line appears in the center of the view.
- `SongEditor.cpp`'s horizontal scrollbar's functionality was changed to make it scroll by ticks instead of bars. This required modifying `TrackContentWidget.cpp` to be positioned by ticks instead of bars to properly draw the grid background.
- Additionally, due to the change in scrollbar step size, the scrolling sensitivity for the Song Editor had to be changed to a reasonable rate. In this PR, the scrolling rate behaves as normal and does not depend on the zooming. I had mentioned the possibility of adding that in the discord, but I decided to save it for another PR.

2024-07-26 02:32 UTC, Rossmaxx reviewed
Minor style review, also pay attention to codefactor. 

Btw you forgot classic theme.

2024-07-26 02:32 UTC, Rossmaxx commented on src/gui/editors/PianoRoll.cpp
> +		if( t > m_currentPosition + w * TimePos::ticksPerBar() / m_ppb )
Style

2024-07-26 02:32 UTC, Rossmaxx commented on src/gui/editors/PianoRoll.cpp
> +		if( t > m_currentPosition + w * TimePos::ticksPerBar() / m_ppb )
In the 3 following lines too

2024-07-26 02:32 UTC, Rossmaxx commented on src/gui/editors/SongEditor.cpp
> +	m_leftRightScroll->setPageStep( 20 * TimePos::ticksPerBar() );
Style here too

2024-07-26 02:32 UTC, Rossmaxx commented on src/gui/editors/SongEditor.cpp
> +	m_leftRightScroll->setMaximum( len * TimePos::ticksPerBar() );
Here too. 
For eg 
```suggestion
	m_leftRightScroll->setMaximum(len * TimePos::ticksPerBar());
```

2024-07-26 02:32 UTC, Rossmaxx commented on src/gui/editors/SongEditor.cpp
> +	if( ( m_song->isPlaying() && m_song->m_playMode == Song::PlayMode::Song ) ||
There's more. See the rest from the diff and correct it.

2024-07-26 02:54 UTC, Rossmaxx commented on src/gui/editors/PianoRoll.cpp
> +		if(t > m_currentPosition + w * TimePos::ticksPerBar() / m_ppb)
Sorry to bug you on style again, but we use spaces between if and the parantheses. I've seen similar style getting repeated. Correct those too.

2024-07-26 03:19 UTC, regulus79 commented
Okay, I made some icons for classic, and hopefully I've fixed all the style issues.

2024-07-26 03:19 UTC, Rossmaxx approved these changes
Looks good.

2024-07-26 14:32 UTC, sakertooth reviewed
We should do testing before merge.

2024-07-26 14:32 UTC, sakertooth commented on src/gui/editors/SongEditor.cpp
> +	else if (abs(we->angleDelta().x()) > abs(we->angleDelta().y())) // scrolling is horizontal
```suggestion
	else if (std::abs(we->angleDelta().x()) > std::abs(we->angleDelta().y())) // scrolling is horizontal
```

2024-07-26 14:32 UTC, sakertooth commented on src/gui/editors/PianoRoll.cpp
> +						TimePos::ticksPerBar() / m_ppb, (tick_t) 0);
```suggestion
			TimePos t2 = std::max(t - w * TimePos::ticksPerBar() *
						TimePos::ticksPerBar() / m_ppb, static_cast<tick_t>(0));
```

2024-07-26 14:32 UTC, sakertooth commented on src/gui/editors/SongEditor.cpp
> +			}
I think this is simpler and should work the same way. Feel free to change the name of `nextPosition` if that's not accurate.
```suggestion
			const auto nextPosition = m_currentPosition + w * TimePos::ticksPerBar() / pixelsPerBar();
			if (t <= nextPosition && t >= m_currentPosition) { return; }
			animateScroll(m_leftRightScroll, t.getTicks(), m_smoothScroll);
```

2024-07-26 14:59 UTC, michaelgregorius commented on src/gui/editors/PianoRoll.cpp
> +	m_scrollBack = (m_timeLine->autoScroll() != TimeLineWidget::AutoScrollState::Disabled);
Parentheses are not needed here.

2024-07-26 15:25 UTC, michaelgregorius commented
I have found a bug that's introduced by this PR, i.e. that is not in master.

## Steps to reproduce
1. Load a song.
2. Set the mode to "Continuous".
3. Play the song.
4. Quickly change to "Off" and then to "Paged".

The line of the play head line will not move with the play head anymore.

2024-07-26 15:27 UTC, michaelgregorius requested changes
The bug that's described in my previous comment should be fixed.

2024-07-26 15:51 UTC, regulus79 commented
I think I found the problem. The return statement in the simplification of the stepped auto scrolling code exited the function too soon, which happened to skip the code for updating the play head line position. I fixed it by modifying the if statement to not require a return.

2024-07-26 15:56 UTC, michaelgregorius approved these changes

2024-07-26 16:03 UTC, sakertooth commented
> I think I found the problem. The return statement in the simplification of the stepped auto scrolling code exited the function too soon, which happened to skip the code for updating the play head line position. I fixed it by modifying the if statement to not require a return.

Had a feeling this would break something, my bad. I got tunnel vision on that one piece of code and forgot about the surrounding function.

2024-07-26 16:18 UTC, sakertooth commented
I think it might be helpful to have more descriptions for the tooltip when toggling between the modes (i.e., you can tell the user what this mode will do in particular rather than simply saying "Auto scrolling", because not all modes auto scroll).

2024-07-26 16:29 UTC, sakertooth approved these changes
LGTM, also something minor I noticed

2024-07-26 16:29 UTC, sakertooth commented on src/gui/editors/SongEditor.cpp
> +							|| m_scrollBack == true)
```suggestion
							|| m_scrollBack)
```

2024-07-26 16:33 UTC, DomClark commented on src/gui/editors/TimeLineWidget.cpp
> +	autoScroll->addState(embed::getIconPixmap("autoscroll_off"), "Auto scrolling disabled");
These tooltips should be translatable:
```suggestion
	autoScroll->addState(embed::getIconPixmap("autoscroll_stepped_on"), tr("Stepped auto scrolling"));
	autoScroll->addState(embed::getIconPixmap("autoscroll_continuous_on"), tr("Continuous auto scrolling"));
	autoScroll->addState(embed::getIconPixmap("autoscroll_off"), tr("Auto scrolling disabled"));
```

2024-07-30 02:53 UTC, regulus79 commented
I realized that changing the scrolling step size also broke zooming centered around the mouse position. I have now fixed that; just a simple multiplication by `TimePos::ticksPerBar()`.

2024-07-30 17:27 UTC, regulus79 commented
Just remembered that there was another bug when drawing the rubberband selection rect, where the left side would get teleported to the left as everything scrolled. Once again, a simple division by `TimePos::ticksPerBar()` fixed it.

2024-07-30 23:38 UTC, regulus79 commented
Alright, I think those are all the necessary changes, so unless anyone spots a new issue, this should pr should be ready to merge.

2024-08-01 15:19 UTC, michaelgregorius approved these changes

2024-08-04 08:30 UTC, merged

2024-08-05 03:43 UTC, Gabrielxd195 commented
I have a question about this, and it is that the continuous scrolling is more fluid and consistent in the Piano Roll than in the Song Editor, since in the latter the scrolling stops suddenly and is not constant. I show you this in the following videos:

Autoscrolling in Piano Roll

https://github.com/user-attachments/assets/af263d05-8b0a-41ac-990e-766862c6f637

Autoscrolling in Song Editor

https://github.com/user-attachments/assets/5af31285-9d37-4554-8600-2e24f58a5b27

Is this on purpose? Or is there some other way to improve this?

2024-08-05 16:48 UTC, regulus79 commented
Ah, whoops, I forgot to test it with smooth scroll enabled. I should have set the scroll using `m_leftRightScroll->setValue()` instead of `animateScroll()`. 

For now, you can temporarily fix it by disabling smooth scroll in the settings.