Fixed MIDI Autodetect always On (#1813)
LMMS/lmms pull request #7564
Opened 2024-10-25 21:51 UTC by Rhodexa

The *Autodetect* checkbox for MIDI Controller Connections is now only enabled if there’s no existing connection between a controller and a parameter. Additionally, the *Autodetect* feature will disengage automatically when a MIDI CC signal is recognized. This prevents accidental reassignment of connections and ensures clear visibility of active controls

2024-10-26 06:54 UTC, szeli1 requested changes
I reviewed your PR, please make the following changes

(DID NOT TEST)

2024-10-26 06:54 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +ControllerConnectionDialog::ControllerConnectionDialog( QWidget * _parent, const AutomatableModel * _target_model ) :
```suggestion
ControllerConnectionDialog::ControllerConnectionDialog(QWidget* _parent, const AutomatableModel* _target_model) :
```

Make sure you follow the style guidelines!

2024-10-26 06:54 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +	m_midiChannelSpinBox = new LcdSpinBox( 2, m_midiGroupBox, tr( "Input channel" ) );
```suggestion
	m_midiChannelSpinBox = new LcdSpinBox(2, m_midiGroupBox, tr("Input channel"));
```

2024-10-26 06:54 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +	m_midiControllerSpinBox = new LcdSpinBox( 3, m_midiGroupBox, tr( "Input controller" ) );
```suggestion
	m_midiControllerSpinBox = new LcdSpinBox(3, m_midiGroupBox, tr("Input controller"));
```

2024-10-26 06:54 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +	m_midiAutoDetectCheckBox = new LedCheckBox( tr("Auto Detect"), m_midiGroupBox, tr("Auto Detect") );
```suggestion
	m_midiAutoDetectCheckBox = new LedCheckBox(tr("Auto Detect"), m_midiGroupBox, tr("Auto Detect"));
```

2024-10-26 06:54 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +			rp_btn->setText( tr( "MIDI-devices to receive MIDI-events from" ) );
Please remove unnecessary white spaces here.

2024-10-26 06:54 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +	// USER CONTROLLER Section
```suggestion
	// User controller section
```

2024-10-26 06:54 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +	// MAPPING FUNCTION Section
```suggestion
	// Mapping function section
```

2024-10-26 06:54 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +	m_midiAutoDetect.setValue( enabled && (!m_targetModel->controllerConnection()) );
```suggestion
	m_midiAutoDetect.setValue(enabled && (!m_targetModel->controllerConnection()));
```

Usual white space issue

2024-10-26 06:54 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +		m_midiAutoDetect.setValue( false );
```suggestion
		m_midiAutoDetect.setValue(false);
```

2024-10-26 06:54 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +// USER CONTROLLER Section logic (Doubles as a Radio-button kinda logic together with MIDI CONTROLLER Section, apparently)
Put this inside the header please

2024-10-26 06:54 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +// MIDI CONTROLLER Section logic (Doubles as a Radio-button kinda logic together with USER CONTROLLER Section, apaprently)
Please add these comments inside the header like this:
```
//! MIDI controller section logic (Doubles as a Radio-button kinda logic together with user controller section, apparently?)
```

2024-10-28 07:00 UTC, Rhodexa commented
Hey, thanks for the feedback, @szeli1, I have revised the entire file to correct code style issues in general. Additionally, I have a also fixed similar issues that were present in the header file. I hope it now adheres better to the ideal structure!

Please let me know if there’s anything else you’d like me to adjust!

2024-10-28 07:15 UTC, szeli1 commented
Usually the only lines that are formatted are the lines that were changed. I'm sorry I didn't mention this before and I'm not sure what should you do with this knowledge. If I were you I would undo these formatting changes for all lines that were not changed.

2024-10-28 07:25 UTC, szeli1 requested changes
This was a style review.

It is difficult to see what was changed because lots of lines are only formatted so it is hard to spot the differences.

2024-10-28 07:25 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +		if(cc && cc->getController()->type() != Controller::ControllerType::Dummy && Engine::getSong())
```suggestion
		if (cc && cc->getController()->type() != Controller::ControllerType::Dummy && Engine::getSong())
```

"if" or "for" and "(" should have a space between.

2024-10-28 07:25 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +	if(!cc) { m_midiGroupBox->model()->setValue(true); }
```suggestion
	if (!cc) { m_midiGroupBox->model()->setValue(true); }
```

2024-10-28 07:25 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +		if(m_readablePorts)
```suggestion
		if (m_readablePorts)
```

2024-10-28 07:25 UTC, szeli1 commented on src/gui/modals/ControllerConnectionDialog.cpp
> +	if(m_midiAutoDetect.value())
```suggestion
	if (m_midiAutoDetect.value())
```

2026-05-19 17:34 UTC, closed without merging